// Scans src/ for Iconify icon names ("prefix:name") and writes an offline
// subset bundle to src/iconData.js, so icons render without any runtime API
// fetch. Run automatically before every build (see package.json "build").
import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs"
import { join, dirname } from "node:path"
import { fileURLToPath } from "node:url"
import { getIconData } from "@iconify/utils"

const __dirname = dirname(fileURLToPath(import.meta.url))
const SRC = join(__dirname, "..", "src")

// Recursively collect every "prefix:name" string in the source tree.
const ICON_RE = /["'`]([a-z0-9-]+):([a-z0-9-]+)["'`]/g
const found = {}
function walk(dir) {
  for (const entry of readdirSync(dir)) {
    const p = join(dir, entry)
    const s = statSync(p)
    if (s.isDirectory()) walk(p)
    else if (/\.(jsx?|tsx?)$/.test(entry)) {
      const txt = readFileSync(p, "utf8")
      let m
      while ((m = ICON_RE.exec(txt))) {
        const [, prefix, name] = m
        ;(found[prefix] ||= new Set()).add(name)
      }
    }
  }
}
walk(SRC)

// Only prefixes we actually ship as installed collections.
const PREFIXES = ["mdi", "ic"]
const exportNames = { mdi: "mdiIcons", ic: "icIcons" }

let out =
  "// Auto-generated by scripts/extract-icons.mjs — do not edit manually.\n" +
  "// Regenerate: node scripts/extract-icons.mjs (runs automatically on build).\n"

for (const prefix of PREFIXES) {
  const names = [...(found[prefix] || [])].sort()
  const collection = JSON.parse(
    readFileSync(
      join(__dirname, "..", "node_modules", "@iconify", "json", "json", `${prefix}.json`),
      "utf8"
    )
  )
  const icons = {}
  const missing = []
  for (const name of names) {
    const data = getIconData(collection, name)
    if (!data) {
      missing.push(name)
      continue
    }
    icons[name] = { body: data.body }
    if (data.width) icons[name].width = data.width
    if (data.height) icons[name].height = data.height
  }
  if (missing.length)
    console.warn(`[icons] ${prefix}: not found -> ${missing.join(", ")}`)

  const bundle = {
    prefix,
    width: collection.width || 24,
    height: collection.height || 24,
    icons,
  }
  out += `export const ${exportNames[prefix]} = ${JSON.stringify(bundle)}\n`
  console.log(`[icons] ${prefix}: bundled ${Object.keys(icons).length} icons`)
}

writeFileSync(join(SRC, "iconData.js"), out)
console.log("[icons] wrote src/iconData.js")
